

# BIND9 WebUI - Production Deployment
# This file uses pre-built images from GitHub Container Registry

services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: bind9-dns
    restart: unless-stopped
    # Use default BIND9 user
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /bind9/config:/etc/bind
      - /bind9/cache:/var/cache/bind
      - /bind9/records:/var/lib/bind
    environment:
      - BIND9_USER=root
      - TZ=UTC
    command: ["/bin/bash", "-c", "echo 'options { directory \"/var/cache/bind\"; forwarders { 8.8.8.8; 8.8.4.4; }; dnssec-validation auto; auth-nxdomain no; listen-on-v6 { any; }; listen-on { any; }; allow-query { any; }; recursion yes; };' > /etc/bind/named.conf && echo '// Do any local configuration here' > /etc/bind/named.conf.local && echo 'zone \".\" { type hint; file \"/usr/share/dns/root.hints\"; };' > /etc/bind/named.conf.default-zones && exec /usr/sbin/named -u root -g"]
    networks:
      - dns-network

  dns-ui-backend:
    image: ghcr.io/kuyapollio/bind9webui-backend:latest
    container_name: dns-ui-backend
    restart: unless-stopped
    # Expose backend port for frontend access
    ports:
      - "3001:3001"
    volumes:
      - /bind9/config:/app/bind9/config
      - /bind9/records:/app/bind9/records
      - backend-data:/app/data
    entrypoint: ["/bin/sh", "-c", "mkdir -p /app/data && exec npm start"]
    environment:
      # Server Configuration
      - NODE_ENV=production
      - PORT=3001
      
      # Authentication - CHANGE THIS SECRET IN PRODUCTION!
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production-please
      
      # File Paths (Docker container paths)
      - BIND9_CONFIG_PATH=/app/bind9/config
      - BIND9_RECORDS_PATH=/app/bind9/records
      - DATA_PATH=/app/data
      
      # Frontend URL (for CORS) - Allow specific origin
      - FRONTEND_URL=http://10.0.0.11:3131
      # Trust proxy for rate limiting
      - TRUST_PROXY=true
      
      # Timezone
      - TZ=UTC
    depends_on:
      - bind9
    networks:
      - dns-network

  dns-ui-frontend:
    image: ghcr.io/kuyapollio/bind9webui-frontend:main
    container_name: dns-ui-frontend
    restart: unless-stopped
    ports:
      - "3131:80"
    environment:
      # API Configuration - Override hardcoded localhost:3001
      - REACT_APP_API_URL=http://10.0.0.11:3001
    depends_on:
      - dns-ui-backend
    networks:
      - dns-network

networks:
  dns-network:
    driver: bridge

volumes:
  bind9-config:
  bind9-cache:
  bind9-records:
  backend-data:
