version: '3.8'

# BIND9 WebUI - Production Deployment
# This file uses pre-built images from GitHub Container Registry

services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: bind9-dns
    restart: unless-stopped
    ports:
      - "${DNS_PORT:-9053}:53/tcp"
      - "${DNS_PORT:-9053}:53/udp"
    volumes:
      - ./bind9/config:/etc/bind:ro
      - bind9-cache:/var/cache/bind
      - bind9-records:/var/lib/bind
    environment:
      - BIND9_USER=bind
      - TZ=${TZ:-UTC}
    networks:
      - dns-network

  dns-ui-backend:
    image: ghcr.io/kuyapollio/bind9webui-backend:latest
    container_name: dns-ui-backend
    restart: unless-stopped
    ports:
      - "${API_PORT:-3001}:3001"
    volumes:
      - ./bind9/config:/app/bind9/config:ro
      - bind9-records:/app/bind9/records
      - backend-data:/app/data
    entrypoint: >
      sh -c "
        mkdir -p /app/data
        exec npm start
      "
    environment:
      # Server Configuration
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3001
      
      # Authentication - CHANGE THIS SECRET IN PRODUCTION!
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-in-production-please}
      
      # File Paths (Docker container paths)
      - BIND9_CONFIG_PATH=/app/bind9/config
      - BIND9_RECORDS_PATH=/app/bind9/records
      - DATA_PATH=/app/data
      
      # Frontend URL (for CORS) - Allow all origins since nginx handles the proxy
      - FRONTEND_URL=*
      
      # Timezone
      - TZ=${TZ:-UTC}
    depends_on:
      bind9:
        condition: service_started
    networks:
      - dns-network

  dns-ui-frontend:
    image: ghcr.io/kuyapollio/bind9webui-frontend:latest
    container_name: dns-ui-frontend
    restart: unless-stopped
    ports:
      - "${WEBUI_PORT:-3131}:80"
    environment:
      # API Configuration - Use relative URL with nginx proxy for Docker network communication
      - REACT_APP_API_URL=/api
    depends_on:
      dns-ui-backend:
        condition: service_started
    networks:
      - dns-network

networks:
  dns-network:
    driver: bridge

volumes:
  bind9-config:
  bind9-cache:
  bind9-records:
  backend-data:
